"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Vendorred from: https://github.com/bentoml/BentoML/blob/main/src/bentoml/grpc/v1/service.proto"""
import abc
import grpc
import service_pb2

class BentoServiceStub:
    """a gRPC BentoServer."""

    def __init__(self, channel: grpc.Channel) -> None: ...
    Call: grpc.UnaryUnaryMultiCallable[
        service_pb2.Request,
        service_pb2.Response,
    ]
    """Call handles methodcaller of given API entrypoint."""
    ServiceMetadata: grpc.UnaryUnaryMultiCallable[
        service_pb2.ServiceMetadataRequest,
        service_pb2.ServiceMetadataResponse,
    ]
    """ServiceMetadata returns metadata of bentoml.Service."""

class BentoServiceServicer(metaclass=abc.ABCMeta):
    """a gRPC BentoServer."""

    @abc.abstractmethod
    def Call(
        self,
        request: service_pb2.Request,
        context: grpc.ServicerContext,
    ) -> service_pb2.Response:
        """Call handles methodcaller of given API entrypoint."""
    @abc.abstractmethod
    def ServiceMetadata(
        self,
        request: service_pb2.ServiceMetadataRequest,
        context: grpc.ServicerContext,
    ) -> service_pb2.ServiceMetadataResponse:
        """ServiceMetadata returns metadata of bentoml.Service."""

def add_BentoServiceServicer_to_server(servicer: BentoServiceServicer, server: grpc.Server) -> None: ...
