"""Find and read Jupytext configuration files"""
from traitlets import Bool
from traitlets import Enum
from traitlets import Float
from traitlets import Unicode
from traitlets import Union
from traitlets.config import Configurable

class JupytextConfiguration(Configurable):
    """Jupytext Configuration's options"""

    formats: Union = ...
    default_jupytext_formats: Unicode = ...
    cell_metadata_filter: Unicode = ...
    default_cell_metadata_filter: Unicode = ...
    comment_magics: Enum = ...
    split_at_heading: Bool = ...
    sphinx_convert_rst2md: Bool = ...
    doxygen_equation_markers: Bool = ...
    outdated_text_notebook_margin: Float = ...
    cm_config_log_level: Enum = ...
    cell_markers: Unicode = ...
    default_cell_markers: Unicode = ...

    notebook_extensions: Union | Unicode = ...
    custom_cell_magics: Unicode = ...
