TRITON_AVAILABLE: bool
AUTOGPTQ_CUDA_AVAILABLE: bool

def dynamically_import_QuantLinear(use_triton: bool, desc_act: bool, group_size: int): ...
def compare_transformers_version(version: str = ..., op: str = ...): ...
def compare_pytorch_version(version: str = ..., op: str = ...): ...
