from typing import Dict
from typing import List

import torch

def copy_blocks(arg0: List[torch.Tensor], arg1: List[torch.Tensor], arg2: Dict[int,List[int]]) -> None: ...
def gather_cached_kv(arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: torch.Tensor, arg4: torch.Tensor) -> None: ...
def reshape_and_cache(arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: torch.Tensor, arg4: torch.Tensor) -> None: ...
def swap_blocks(arg0: torch.Tensor, arg1: torch.Tensor, arg2: Dict[int,int]) -> None: ...
