import enum

from _typeshed import Incomplete

class Device(enum.Enum):
    GPU: Incomplete
    CPU: Incomplete

class Counter:
    counter: Incomplete
    def __init__(self, start: int = ...) -> None: ...
    def __next__(self) -> int: ...
    def reset(self) -> None: ...

def get_gpu_memory(gpu: int = ...) -> int: ...
def get_cpu_memory() -> int: ...
def random_uuid() -> str: ...
def in_wsl() -> bool: ...
