"""This type stub file was generated by pyright."""

class CancellableStream:
    """Stream wrapper for real-time events, logs, etc. from the server.

    Example:
        >>> events = client.events()
        >>> for event in events:
        ...   print(event)
        >>> # and cancel from another thread
        >>> events.close()
    """

    def __init__(self, stream, response) -> None: ...
    def __iter__(self): ...
    def __next__(self): ...

    next = ...
    def close(self):  # -> None:
        """Closes the event streaming."""
        ...
