"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Vendorred from: https://github.com/bentoml/BentoML/blob/main/src/bentoml/grpc/v1/service.proto"""
import abc
import collections.abc
import grpc
import grpc.aio
import service_pb2
import typing

_T = typing.TypeVar('_T')

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta):
    ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore
    ...

class BentoServiceStub:
    """a gRPC BentoServer."""

    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Call: grpc.UnaryUnaryMultiCallable[
        service_pb2.Request,
        service_pb2.Response,
    ]
    """Call handles methodcaller of given API entrypoint."""
    ServiceMetadata: grpc.UnaryUnaryMultiCallable[
        service_pb2.ServiceMetadataRequest,
        service_pb2.ServiceMetadataResponse,
    ]
    """ServiceMetadata returns metadata of bentoml.Service."""

class BentoServiceAsyncStub:
    """a gRPC BentoServer."""

    Call: grpc.aio.UnaryUnaryMultiCallable[
        service_pb2.Request,
        service_pb2.Response,
    ]
    """Call handles methodcaller of given API entrypoint."""
    ServiceMetadata: grpc.aio.UnaryUnaryMultiCallable[
        service_pb2.ServiceMetadataRequest,
        service_pb2.ServiceMetadataResponse,
    ]
    """ServiceMetadata returns metadata of bentoml.Service."""

class BentoServiceServicer(metaclass=abc.ABCMeta):
    """a gRPC BentoServer."""

    @abc.abstractmethod
    def Call(
        self,
        request: service_pb2.Request,
        context: _ServicerContext,
    ) -> typing.Union[service_pb2.Response, collections.abc.Awaitable[service_pb2.Response]]:
        """Call handles methodcaller of given API entrypoint."""
    @abc.abstractmethod
    def ServiceMetadata(
        self,
        request: service_pb2.ServiceMetadataRequest,
        context: _ServicerContext,
    ) -> typing.Union[service_pb2.ServiceMetadataResponse, collections.abc.Awaitable[service_pb2.ServiceMetadataResponse]]:
        """ServiceMetadata returns metadata of bentoml.Service."""

def add_BentoServiceServicer_to_server(servicer: BentoServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
