blank_issues_enabled: true
version: 2.1
contact_links:
  - name: Blank issues
    url: https://github.com/bentoml/openllm/issues/new
    about: To create a blank issue
  - name: BentoML Discussions
    url: https://github.com/bentoml/openllm/discussions
    about: Please ask general questions here.
