# fmt: off
# AUTOGENERATED BY update-config-stubs.py. DO NOT EDIT
from .configuration_auto import CONFIG_MAPPING as CONFIG_MAPPING, CONFIG_MAPPING_NAMES as CONFIG_MAPPING_NAMES, AutoConfig as AutoConfig
from .configuration_baichuan import BaichuanConfig as BaichuanConfig
from .configuration_chatglm import ChatGLMConfig as ChatGLMConfig
from .configuration_commandr import CohereConfig as CohereConfig
from .configuration_dbrx import DbrxConfig as DbrxConfig
from .configuration_dolly_v2 import DollyV2Config as DollyV2Config
from .configuration_falcon import FalconConfig as FalconConfig
from .configuration_gemma import GemmaConfig as GemmaConfig
from .configuration_gpt_neox import GPTNeoXConfig as GPTNeoXConfig
from .configuration_llama import LlamaConfig as LlamaConfig
from .configuration_mistral import MistralConfig as MistralConfig
from .configuration_mixtral import MixtralConfig as MixtralConfig
from .configuration_mpt import MPTConfig as MPTConfig
from .configuration_opt import OPTConfig as OPTConfig
from .configuration_phi import PhiConfig as PhiConfig
from .configuration_qwen import QwenConfig as QwenConfig
from .configuration_stablelm import StableLMConfig as StableLMConfig
from .configuration_starcoder import StarCoderConfig as StarCoderConfig
from .configuration_yi import YiConfig as YiConfig
