# Generated by tools/update-brew-tap.py. DO NOT EDIT!
# Please refers to the original template file Formula/openllm.rb.j2
# vim: set ft=ruby:
class Openllm < Formula
  desc "OpenLLM: Operating LLMs in production"
  homepage "https://github.com/bentoml/OpenLLM"
  version "0.4.17"
  license "Apache-2.0"
  head "https://github.com/bentoml/OpenLLM, branch: main"
  url "https://github.com/bentoml/OpenLLM/archive/v0.4.17.tar.gz"
  sha256 "220903ec1ecf82b1879506aad9e8223815f887b45e0cd3a3914fa300c16e2108"

  on_linux do
    url "https://github.com/bentoml/OpenLLM/releases/download/v0.4.17/openllm-0.4.17-x86_64-unknown-linux-musl.tar.gz"
    sha256 "4b37bc561b1c4c57d41e02680802308f6dafa6c20708f15e3f5ced2aae3fed88"
  end
  on_macos do
    on_arm do
      url "https://github.com/bentoml/OpenLLM/releases/download/v0.4.17/openllm-0.4.17-aarch64-apple-darwin.tar.gz"
      sha256 "1c761d355e437943c8d3f32e766cd3e2fe87a86866dc9ea178548d5b2976fffa"
    end
    on_intel do
      url "https://github.com/bentoml/OpenLLM/releases/download/v0.4.17/openllm-0.4.17-x86_64-apple-darwin.tar.gz"
      sha256 "b047d83b1131f423940a219c72451dc6a6146b5189e6d205fb1402b81c6af336"
    end
  end

  def install
    on_linux do
      bin.install "openllm-0.4.17-x86_64-unknown-linux-musl" => "openllm"
    end
  on_macos do
    on_arm do
      bin.install "openllm-0.4.17-aarch64-apple-darwin" => "openllm"
    end
    on_intel do
      bin.install "openllm-0.4.17-x86_64-apple-darwin" => "openllm"
    end
  end
    ohai "To get started, run: 'openllm --help'"
    ohai "To see supported models, run: 'openllm models'"
  end

  test do
    shell_output "#{bin}/openllm --version"
  end
end
