"""
This type stub file was generated by pyright.
"""

import urllib3
from docker.transport.basehttpadapter import BaseHTTPAdapter

""" Resolves OpenSSL issues in some servers:
      https://lukasa.co.uk/2013/01/Choosing_SSL_Version_In_Requests/
      https://github.com/kennethreitz/requests/pull/799
"""
PoolManager = urllib3.poolmanager.PoolManager

class SSLHTTPAdapter(BaseHTTPAdapter):
    """An HTTPS Transport Adapter that uses an arbitrary SSL version."""

    __attrs__ = ...
    def __init__(self, ssl_version=..., assert_hostname=..., assert_fingerprint=..., **kwargs) -> None: ...
    def init_poolmanager(self, connections, maxsize, block=...): ...
    def get_connection(self, *args, **kwargs):
        """
        Ensure assert_hostname is set correctly on our pool

        We already take care of a normal poolmanager via init_poolmanager

        But we still need to take care of when there is a proxy poolmanager
        """
        ...
    def can_override_ssl_version(self): ...
