"""This type stub file was generated by pyright."""

class Store:
    def __init__(self, program, environment=...) -> None:
        """Create a store object that acts as an interface to
        perform the basic operations for storing, retrieving
        and erasing credentials using `program`.
        """
        ...
    def get(self, server):  # -> Any:
        """Retrieve credentials for `server`. If no credentials are found,
        a `StoreError` will be raised.
        """
        ...
    def store(self, server, username, secret):  # -> bytes:
        """Store credentials for `server`. Raises a `StoreError` if an error
        occurs.
        """
        ...
    def erase(self, server):  # -> None:
        """Erase credentials for `server`. Raises a `StoreError` if an error
        occurs.
        """
        ...
    def list(self):  # -> Any:
        """List stored credentials. Requires v0.4.0+ of the helper."""
        ...
