"""
This type stub file was generated by pyright.
"""

def create_environment_dict(overrides):  # -> dict[str, str]:
    """
    Create and return a copy of os.environ with the specified overrides
    """
    ...
