from _typeshed import Incomplete
from nbformat.notebooknode import NotebookNode as NotebookNode

nbformat: int
nbformat_minor: int
nbformat_schema: Incomplete

def validate(node, ref: Incomplete | None = ...): ...
def new_output(output_type, data: Incomplete | None = ..., **kwargs): ...
def output_from_msg(msg): ...
def new_code_cell(source: str = ..., **kwargs): ...
def new_markdown_cell(source: str = ..., **kwargs): ...
def new_raw_cell(source: str = ..., **kwargs): ...
def new_notebook(**kwargs): ...
