from typing import Any

from _typeshed import Incomplete
from nbformat.notebooknode import NotebookNode as NotebookNode
nbformat: int
nbformat_minor: int
nbformat_schema: Incomplete

def validate(node: NotebookNode, ref: Incomplete | None = ...) -> Any: ...
def new_output(output_type: Any, data: Incomplete | None = ..., **kwargs: Any) -> Any: ...
def output_from_msg(msg: str) -> Any: ...
def new_code_cell(source: str = ..., **kwargs: Any) -> NotebookNode: ...
def new_markdown_cell(source: str = ..., **kwargs: Any) -> NotebookNode: ...
def new_raw_cell(source: str = ..., **kwargs: Any) -> NotebookNode: ...
def new_notebook(**kwargs: Any) -> NotebookNode: ...
