"""
This type stub file was generated by pyright.
"""

import json

from .rwbase import NotebookReader
from .rwbase import NotebookWriter

"""Read and write notebooks in JSON format."""

class BytesEncoder(json.JSONEncoder):
    """A JSON encoder that accepts b64 (and other *ascii*) bytestrings."""

    def default(self, obj):  # -> str | Any:
        """Get the default value of an object."""
        ...

class JSONReader(NotebookReader):
    """A JSON notebook reader."""

    def reads(self, s, **kwargs):
        """Read a JSON string into a Notebook object"""
        ...
    def to_notebook(self, d, **kwargs):
        """Convert a disk-format notebook dict to in-memory NotebookNode

        handles multi-line values as strings, scrubbing of transient values, etc.
        """
        ...

class JSONWriter(NotebookWriter):
    """A JSON notebook writer."""

    def writes(self, nb, **kwargs):  # -> str:
        """Serialize a NotebookNode object as a JSON string"""
        ...

_reader = ...
_writer = ...
reads = ...
read = ...
to_notebook = ...
write = ...
writes = ...
