def rejoin_lines(nb): ...
def split_lines(nb): ...
def strip_transient(nb): ...

class NotebookReader:
    def reads(self, s, **kwargs) -> None: ...
    def read(self, fp, **kwargs): ...

class NotebookWriter:
    def writes(self, nb, **kwargs) -> None: ...
    def write(self, nb, fp, **kwargs): ...
