#!/bin/bash

set -e

GIT_ROOT=$(git rev-parse --show-toplevel)

cd "$GIT_ROOT" || exit 1

# NOTE that we are using local bazel instead of system bazel.
bazel run //requirements:pypi.update
bazel run //:vendor-pypi
bazel run //requirements:tensorflow.update
bazel run //:vendor-tensorflow
bazel run //requirements:tests.update
bazel run //:vendor-tests
