#!/usr/bin/env bash

# Check if yapf is installed, otherwise exit 1
[[ -x "$(command -v yapf)" ]] || (
    echo "yapf not found"
    exit 1
)

yapf -pri openllm-python/** 2>/dev/null
yapf -pri  openllm-core/** 2>/dev/null
yapf -pri  openllm-client/** 2>/dev/null
