# This file is generated by tools/update-dummy.py. DO NOT EDIT MANUALLY!
# To update this, run ./tools/update-dummy.py
from __future__ import annotations
import typing as _t
from openllm.utils import DummyMetaclass as _DummyMetaclass, require_backends as _require_backends
class GGMLLlama(metaclass=_DummyMetaclass):
  _backends=["ctransformers","fairscale","sentencepiece"]
  def __init__(self,*param_decls:_t.Any,**attrs: _t.Any):_require_backends(self,["ctransformers","fairscale","sentencepiece"])
class AutoGGML(metaclass=_DummyMetaclass):
  _backends=["ctransformers"]
  def __init__(self,*param_decls:_t.Any,**attrs: _t.Any):_require_backends(self,["ctransformers"])
MODEL_GGML_MAPPING_NAMES:_t.Any=None
__all__:list[str]=["MODEL_GGML_MAPPING_NAMES","AutoGGML","GGMLLlama"]
