# This file is generated by tools/update-dummy.py. DO NOT EDIT MANUALLY!
# To update this, run ./tools/update-dummy.py
from __future__ import annotations
import typing as _t
from openllm_core.utils import DummyMetaclass as _DummyMetaclass, require_backends as _require_backends
class FlaxFlanT5(metaclass=_DummyMetaclass):
  _backends=["flax"]
  def __init__(self,*param_decls:_t.Any,**attrs: _t.Any):_require_backends(self,["flax"])
class FlaxOPT(metaclass=_DummyMetaclass):
  _backends=["flax"]
  def __init__(self,*param_decls:_t.Any,**attrs: _t.Any):_require_backends(self,["flax"])
class AutoFlaxLLM(metaclass=_DummyMetaclass):
  _backends=["flax"]
  def __init__(self,*param_decls:_t.Any,**attrs: _t.Any):_require_backends(self,["flax"])
MODEL_FLAX_MAPPING_NAMES:_t.Any=None
__all__:list[str]=["MODEL_FLAX_MAPPING_NAMES","AutoFlaxLLM","FlaxFlanT5","FlaxOPT"]
