name: slash-command-dispatch
on:
  issue_comment:
    types: [created, edited]
jobs:
  slash-command-dispatch:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: ${{ github.event.issue.pull_request }} && github.repository_owner == 'bentoml'
    steps:
      - uses: actions/checkout@v3
      - name: Slash command setup
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.OPENLLM_PAT }}
          issue-type: pull-request
          commands: update-changelog
          permission: write
