from transformers import LogitsProcessorList, PretrainedConfig

from openllm_core import LLMConfig

def prepare_logits_processor(config: LLMConfig) -> LogitsProcessorList: ...
def get_context_length(config: PretrainedConfig) -> int: ...
def is_sentence_complete(output: str) -> bool: ...
def is_partial_stop(output: str, stop_str: str) -> bool: ...
